version: '3'
services:
  postgres:
    image: debezium/postgres:12
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-pw
      POSTGRES_DB: customers
    volumes:
      - ./postgres/custom-config.conf:/etc/postgresql/postgresql.conf
      - ./postgres/db-init-scripts:/docker-entrypoint-initdb.d
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    #restart: unless-stopped
    #network_mode: bridge
    ports:
      # HTTP
      - 8080:8080/tcp
      # HTTPS
      - 8443:8443/tcp
      # Remote Input Socket
      - 10000:10000/tcp
      # JVM Debugger
      - 8000:8000/tcp
      # Cluster Node Protocol
      #- 11443:11443/tcp
    volumes:
      # mkdir /var/lib/nifi && chown -R 1000:1000 /var/lib/nifi
      - ./database_repository:/opt/nifi/nifi-current/database_repository
      - ./flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./content_repository:/opt/nifi/nifi-current/content_repository
      - ./provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./state:/opt/nifi/nifi-current/state
      - ./logs:/opt/nifi/nifi-current/logs
      - ./contenido_lab:/home/nifi/contenido_lab
      - ./salidas:/tmp
      
      # A custom nifi.properties file can be mounted as follows.
      #- /var/lib/nifi/conf/nifi.properties:/opt/nifi/nifi-current/conf/nifi.properties:ro

    environment:
 
      NIFI_WEB_HTTP_HOST: '0.0.0.0'
      
      NIFI_WEB_HTTP_PORT: 8080

      SINGLE_USER_CREDENTIALS_USERNAME: 'admin'
      SINGLE_USER_CREDENTIALS_PASSWORD: 'password123456'